# Generated by Django 2.2 on 2020-08-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200806_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='inage',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
