# Generated by Django 2.2 on 2020-08-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_inage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='inage',
            new_name='image',
        ),
    ]
